### ISSUE TITLE
How to prevent duplicate entries?

### ISSUE THREAD

**Issue by j8r** [weareinteractive/ansible-cron#11]
In `/etc/crontab`, we want to change the cron hourly, daily, weekly and monthly.
They are defined by default, so new entries managed by Ansible are added (`#Ansible: `).
The problem is this crons will now be executed twice.

One way to solve this is to use a template instead the standard `cron` module, which is kind of a pity.

**Comment by j8r** [comment]
I guess we have to remove the file when creating the VM image to solve the issue.

**Comment by franklinkim** [comment]
Hi, sorry for the late reply. 
Yes, this role doesn't manage the `/etc/crontab` file yet but PR are always welcome!
